### ISSUE TITLE
Desktop environment is not complete

### ISSUE THREAD

**Issue by 0wn3r** [LinuxCNC/linuxcnc-live-build#1]
Currently Buster ISO is missing some really essential packages like thunar-archive-plugin, bash-completion, openssh-server. I believe first is due to missing task-xfce-desktop meta package with an intention to keep image smaller, but stretch image is still lower in size having this one included: https://github.com/jepler/stretch-live-build/blob/master/do.sh
Is there a way to include those from Stretch ISO?

**Comment by petterreinholdtsen** [comment]
Only by rebuilding the live ISO after modifyingconfig/package-lists/desktop.list or neighboring file, I believe.  Notice the stretch live image had a lot more firmware packages too.  It also had three packages I fail to find in Debian:  nopaste, f-engrave and truetype-tracer.  Not sure where these came from.

A patch similar to thise one might be useful, but will increase the ISO size:

```
diff --git a/config/package-lists/desktop.list b/config/package-lists/desktop.list
index b9cfca4..87924b3 100644
--- a/config/package-lists/desktop.list
+++ b/config/package-lists/desktop.list
@@ -1,6 +1,7 @@
 lightdm
 xfce4
 xfce4-terminal
+task-xfce-desktop
 lsb-release
 nm-tray
 pciutils
@@ -10,3 +11,38 @@ firefox-esr
 atril
 mlocate
 isenkram
+amd64-microcode
+atmel-firmware
+bash-completion
+bladerf-firmware-fx3
+bluez-firmware
+build-essential
+firmware-amd-graphics
+firmware-atheros
+firmware-b43-installer
+firmware-b43legacy-installer
+firmware-bnx2
+firmware-bnx2x
+firmware-brcm80211
+firmware-cavium
+firmware-intelwimax
+firmware-ipw2x00
+firmware-iwlwifi
+firmware-libertas
+firmware-linux
+firmware-linux-free
+firmware-misc-nonfree
+firmware-myricom
+firmware-netxen
+firmware-qlogic
+firmware-realtek
+firmware-ti-connectivity
+firmware-zd1211
+galculator
+gparted
+hdmi2usb-fx2-firmware
+intel-microcode
+linux-perf
+mesa-utils
+openssh-server
+vim-gtk3
```

Note, this patch is relative to my work on a bookworm ISO, so not directly applicable.

**Comment by silopolis** [comment]
Le mar. 26 juil. 2022 à 08:50, petterreinholdtsen ***@***.***>
a écrit :

>  It also had three packages I fail to find in Debian: nopaste, f-engrave
> and truetype-tracer. Not sure where these came from.
>

Our own repo?

A patch similar to thise one might be useful, but will increase the ISO
> size:
>

Hard to really ponder this with unlimited fiber Internet access at home!
sadly not everyone is enjoying such useless bandwidth around the world...

Spontaneously, my choice would be to favor UX once ISO is downloaded, so
include all and everything needed for user to enjoy its trial and, and
reduce potential support requests about live cd usage

BTW, as @TurBoss is making progress packaging QtPyVCP for Debian, I would
also include it, in fine

**Comment by petterreinholdtsen** [comment]
[Jérémie Tarot]
> Our own repo?

No idea, did not look for them. :)

> Spontaneously, my choice would be to favor UX once ISO is downloaded, so
> include all and everything needed for user to enjoy its trial and, and
> reduce potential support requests about live cd usage

I get parse error here.  My best guess is that you are positive to add
more packages to the live CD.

> BTW, as @TurBoss is making progress packaging QtPyVCP for Debian, I
> would also include it, in fine

Once it is in Debian, it will be trivial to include in the Debian
Testing based live build.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by silopolis** [comment]
Le mar. 26 juil. 2022 à 21:47, petterreinholdtsen ***@***.***>
a écrit :

>
> I get parse error here. My best guess is that you are positive to add
> more packages to the live CD.
>


Exactly


> BTW, as @TurBoss is making progress packaging QtPyVCP for Debian, I
> > would also include it, in fine
>
> Once it is in Debian, it will be trivial to include in the Debian
> Testing based live build.


Awesome
