### ISSUE TITLE
Using on Linux Mint 19.2 (Ubuntu Bionic)

### ISSUE THREAD

**Issue by ozzyrob** [LinuxCNC/linuxcnc-live-build#2]
Maye not an issue as such but to use with Linux Mint 19.2 I had to install Live-Build from Buster and started the build with:

```
sudo lb config --distribution Buster
sudo lb build
```

ISO was built and run with a quick test under VBox

**Comment by petterreinholdtsen** [comment]
Is this still needed?  auto/config in the buster branch list --distribution buster too, and it should be enough.

**Comment by rodw-au** [comment]
I think its too old to be still relevant. I suggest it should be closed. 
I was actually thinking right now that adding Sebs repo as per #9 in the getting linuxcnc docs might work on Mint. But it would not need all of the pinning http://linuxcnc.org/docs/2.9/html/getting-started/getting-linuxcnc.html#_updating_linuxcnc_on_debian_bookworm_x86_only

**Comment by rodw-au** [comment]
Issue relates to a non-debian distro.
Now the bookworm branch has been updated,
I recommend this issue be closed.

**Comment by ghost** [comment]
Yeah for sure haven’t looked at this for ages, can’t even remember the post.
